echo "========================================================"
echo " ⚡ HOMEBRIDGE UXC MASTER INITIALIZATION ENGINE ⚡"
echo "========================================================"
printf '\n\n\n'

# ==============================================================================
# PART 1: MASTER CONFIGURATION VARIABLES (Central Variables Hub)
# ==============================================================================

# ==============================================================================
# GITHUB DOWNLOAD CONFIGURATION
# ==============================================================================
BUNDLE_URL="https://github.com/micpro7/openwrt-uxc-homebridge/releases/latest/download/homebridge-arm64.tar.gz"
ARCHIVE="/mnt/X6/homebridge.tar.gz"

# ==============================================================================
# CONFIGURATION VARIABLES (Edit these to tune your deployment)
# ==============================================================================
CONTAINER_NAME="homebridge"
TARGET_MOUNT="/mnt/X6"                     # Physical host SSD mount point
BUNDLE_PATH="/mnt/X6/UXC/homebridge"       # Target path for config.json and rootfs
PERSISTENT_DATA_SOURCE="/mnt/X6/homebridge-data" # Path for persistent accessory configurations

# ==============================================================================
# ENVIRONMENT VARIABLES & PERFORMANCE TUNING
# ==============================================================================
TIMEZONE="Europe/London"                   # Local system timezone
MDNS_NET_INTERFACE="br-lan"                # Interface for Homebridge mDNS broadcasts
NODE_MEMORY_LIMIT="256"                    # Max Node.js heap memory limit in MB
THREAD_POOL_SIZE="4"                       # Number of Libuv worker threads
BIND_IP="0.0.0.0"                          # Binding address for Homebridge UI

# Security Parameters
NO_NEW_PRIVILEGES=false                    # Restrict container child process escalation (true/false)
# ==============================================================================


# ==============================================================================
# PHASE 0.5: CREATE CENTRAL VARIABLE ENVIRONMENT FILE
# ==============================================================================
echo "📝 Creating persistent Homebridge variable map..."

cat > /etc/homebridge.conf << EOF
# Auto-generated by Homebridge UXC Master Initialization Engine

CONTAINER_NAME="$CONTAINER_NAME"
TARGET_MOUNT="$TARGET_MOUNT"
BUNDLE_PATH="$BUNDLE_PATH"
PERSISTENT_DATA_SOURCE="$PERSISTENT_DATA_SOURCE"

TIMEZONE="$TIMEZONE"
MDNS_NET_INTERFACE="$MDNS_NET_INTERFACE"
NODE_MEMORY_LIMIT="$NODE_MEMORY_LIMIT"
THREAD_POOL_SIZE="$THREAD_POOL_SIZE"
BIND_IP="$BIND_IP"

NO_NEW_PRIVILEGES="$NO_NEW_PRIVILEGES"
EOF

chmod 600 /etc/homebridge.conf

echo "✅ Central variable map saved to /etc/homebridge.conf"
echo "========(+) DONE ✅ (+)========"
printf '\n\n\n'


# ==========================================
# Phase 1: Environment & Dependency Check
# ==========================================
echo "🔄 [Phase 1] Syncing OpenWrt core infrastructure dependencies..."

apk update
apk add uxc procd-ujail kmod-veth jq

echo "========(+) DONE ✅ (+)========"
printf '\n\n\n'


# ==========================================
# Phase 2: Runtime Workspace Purge
# ==========================================
echo "🧹 [Phase 2] Clearing out stale runtime structures..."

uxc kill "$CONTAINER_NAME" 2>/dev/null || true
uxc delete "$CONTAINER_NAME" --force 2>/dev/null || true

echo "========(+) DONE ✅ (+)========"
printf '\n\n\n'


# ==========================================
# Phase 3: Structural Path Assembly
# ==========================================
echo "📂 [Phase 3] Constructing host storage target directories..."

rm -rf "$BUNDLE_PATH"

mkdir -p "$BUNDLE_PATH"
mkdir -p "$PERSISTENT_DATA_SOURCE"

sync

echo "========(+) DONE ✅ (+)========"
printf '\n\n\n'


# ==========================================
# Phase 4: Bundle Fetch & Verification
# ==========================================
echo "📥 [Phase 4] Pulling production blueprint package from GitHub..."

wget -O "$ARCHIVE" "$BUNDLE_URL"

printf '\n\n\n'

echo "📦 Extracting package payload onto $TARGET_MOUNT storage..."

tar -xpf "$ARCHIVE" -C "$BUNDLE_PATH"

sync

rm -f "$ARCHIVE"

printf '\n\n\n'


if [ -f "$BUNDLE_PATH/config.json" ] && [ -d "$BUNDLE_PATH/rootfs" ]; then

    echo "   config.json validated  ✅"
    echo "   rootfs engine verified ✅"
    echo "🚀 OCI application bundle fully authenticated."

else

    echo "❌ [ERROR] Structural corruption detected during extraction. Halting deployment."
    exit 1

fi


echo "========(+) DONE ✅ (+)========"
printf '\n\n\n'

# ==========================================
# Phase 5: Dynamic Variable Injection (JQ Splits)
# ==========================================
echo "📝 [Phase 5] Injecting master variable matrix via individual JQ splits..."

if [ -f "$BUNDLE_PATH/config.json" ]; then

    # Split 1: Update Persistent Storage Path Mount Source
    jq --arg src "$PERSISTENT_DATA_SOURCE" \
        '.mounts = (.mounts | map(if .destination == "/var/lib/homebridge" then .source = $src else . end))' \
        "$BUNDLE_PATH/config.json" > "$BUNDLE_PATH/config.json.tmp" && mv "$BUNDLE_PATH/config.json.tmp" "$BUNDLE_PATH/config.json"

    echo "   ↳ Mount Target bound to: $PERSISTENT_DATA_SOURCE ✅"


    # Split 2: Update Timezone (TZ)
    jq --arg tz "TZ=$TIMEZONE" \
        '.process.env = (.process.env | map(if startswith("TZ=") then $tz else . end))' \
        "$BUNDLE_PATH/config.json" > "$BUNDLE_PATH/config.json.tmp" && mv "$BUNDLE_PATH/config.json.tmp" "$BUNDLE_PATH/config.json"

    echo "   ↳ Timezone assigned to: $TIMEZONE ✅"


    # Split 3: Update MDNS Interface Network Bridge
    jq --arg mdns "MDNS_INTERFACE=$MDNS_NET_INTERFACE" \
        '.process.env = (.process.env | map(if startswith("MDNS_INTERFACE=") then $mdns else . end))' \
        "$BUNDLE_PATH/config.json" > "$BUNDLE_PATH/config.json.tmp" && mv "$BUNDLE_PATH/config.json.tmp" "$BUNDLE_PATH/config.json"

    echo "   ↳ mDNS broadcast mapped to: $MDNS_NET_INTERFACE ✅"


    # Split 4: Update Node.js Old Space Memory Constraints
    jq --arg node_opt "NODE_OPTIONS=--max-old-space-size=$NODE_MEMORY_LIMIT" \
        '.process.env = (.process.env | map(if startswith("NODE_OPTIONS=") then $node_opt else . end))' \
        "$BUNDLE_PATH/config.json" > "$BUNDLE_PATH/config.json.tmp" && mv "$BUNDLE_PATH/config.json.tmp" "$BUNDLE_PATH/config.json"

    echo "   ↳ Node engine memory threshold set to: ${NODE_MEMORY_LIMIT}MB ✅"


    # Split 5: Update Libuv Thread Pool Allocation
    jq --arg threads "UV_THREADPOOL_SIZE=$THREAD_POOL_SIZE" \
        '.process.env = (.process.env | map(if startswith("UV_THREADPOOL_SIZE=") then $threads else . end))' \
        "$BUNDLE_PATH/config.json" > "$BUNDLE_PATH/config.json.tmp" && mv "$BUNDLE_PATH/config.json.tmp" "$BUNDLE_PATH/config.json"

    echo "   ↳ Libuv backend worker threads balanced at: $THREAD_POOL_SIZE ✅"


    # Split 6: Update Homebridge Binding IP Target
    jq --arg ip "HOMEBRIDGE_IP=$BIND_IP" \
        '.process.env = (.process.env | map(if startswith("HOMEBRIDGE_IP=") then $ip else . end))' \
        "$BUNDLE_PATH/config.json" > "$BUNDLE_PATH/config.json.tmp" && mv "$BUNDLE_PATH/config.json.tmp" "$BUNDLE_PATH/config.json"

    echo "   ↳ Network socket interface listening on: $BIND_IP ✅"


    # Split 7: Toggle Kernel Security Boundaries
    jq --argjson nnp "$NO_NEW_PRIVILEGES" \
        '.process.noNewPrivileges = $nnp' \
        "$BUNDLE_PATH/config.json" > "$BUNDLE_PATH/config.json.tmp" && mv "$BUNDLE_PATH/config.json.tmp" "$BUNDLE_PATH/config.json"

    echo "   ↳ Kernel privilege escalation guard: $NO_NEW_PRIVILEGES ✅"


    logger -t homebridge_boot "All individual configuration targets processed."

fi


printf '\n\n\n'

echo "⚙️ OCI JSON blueprints compiled permanently onto SSD."
echo "========(+) DONE ✅ (+)========"
printf '\n\n\n'


# ==========================================
# Phase 6: Container Registration & Ignition
# ==========================================
echo "🏗️ [Phase 6] Registering container blueprint with UXC engine..."


uxc create "$CONTAINER_NAME" \
    --bundle "$BUNDLE_PATH" \
    --mounts "$TARGET_MOUNT"


printf '\n\n\n'


echo "⏳ Holding engine execution for stabilization (3s)..."

sleep 3


printf '\n\n\n'


echo "🏁 Spawning Homebridge runtime daemon..."

uxc start "$CONTAINER_NAME"


printf '\n\n\n'


echo "✨ Active container framework status verified:"

uxc list

echo "========(+) DONE ✅ (+)========"
printf '\n\n\n'


# ==============================================================================
# PART 7: INSTALL PERSISTENT PROCD STARTUP SERVICE
# ==============================================================================
echo "🛠️ Installing persistent Homebridge procd startup service..."


cat > /etc/init.d/homebridge << 'EOF'
#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1


# ==============================================================================
# LOAD MASTER VARIABLES
# ==============================================================================

if [ -f /etc/homebridge.conf ]; then
    . /etc/homebridge.conf
else
    logger -t homebridge_init "[CRITICAL ERROR] Missing /etc/homebridge.conf"
    exit 1
fi



start_service() {

    logger -t homebridge_init "Waiting for $TARGET_MOUNT to become available..."


    for i in $(seq 1 30); do

        if grep -qs " $TARGET_MOUNT " /proc/mounts; then

            logger -t homebridge_init "$TARGET_MOUNT mounted successfully on loop $i."
            break

        fi

        sleep 1

    done



    if ! grep -qs " $TARGET_MOUNT " /proc/mounts; then

        logger -t homebridge_init "[CRITICAL ERROR] $TARGET_MOUNT failed to mount."
        return 1

    fi



    if [ ! -f "$BUNDLE_PATH/config.json" ]; then

        logger -t homebridge_init "[CRITICAL ERROR] Missing config.json."
        return 1

    fi



    logger -t homebridge_init "Cleaning previous UXC state..."

    /sbin/uxc kill "$CONTAINER_NAME" >/dev/null 2>&1
    /sbin/uxc delete "$CONTAINER_NAME" --force >/dev/null 2>&1



    logger -t homebridge_init "Creating Homebridge UXC container..."


    if /sbin/uxc create "$CONTAINER_NAME" \
        --bundle "$BUNDLE_PATH" \
        --mounts "$TARGET_MOUNT"; then


        logger -t homebridge_init "UXC container created successfully."


    else

        logger -t homebridge_init "[CRITICAL ERROR] UXC create failed."
        return 1

    fi



    sleep 3



    procd_open_instance

    procd_set_param command /sbin/uxc start "$CONTAINER_NAME"

    procd_close_instance



    logger -t homebridge_init "Homebridge startup command issued successfully."

}



stop_service() {

    logger -t homebridge_init "Stopping Homebridge..."

    /sbin/uxc kill "$CONTAINER_NAME" --signal TERM >/dev/null 2>&1

}



status() {

    if [ -x /sbin/uxc ]; then

        STATUS=$(/sbin/uxc state "$CONTAINER_NAME" 2>/dev/null)

        echo "$STATUS"

    else

        echo "Error: /sbin/uxc not found."

    fi

}

EOF


chmod +x /etc/init.d/homebridge


/etc/init.d/homebridge enable


echo "✅ Persistent Homebridge procd service installed."

echo "========(+) DONE ✅ (+)========"
printf '\n\n\n'


echo "🎉 ======== MASTER PIPELINE DEPLOYMENT COMPLETE ======== 🎉"